export const IMAGE_LIST_SET = 'IMAGE_LIST_SET';
export const IMAGE_LIST_FETCH = 'IMAGE_LIST_FETCH';

export const IMAGE_HIDE = 'IMAGE_HIDE';
export const IMAGE_TOGGLE = 'IMAGE_TOGGLE';

export const IMAGE_VIEWER_OPEN = 'IMAGE_VIEWER_OPEN';
export const IMAGE_VIEWER_CLOSE = 'IMAGE_VIEWER_CLOSE';

export const IMAGE_VIEWER_NEXT = 'IMAGE_VIEWER_NEXT';
export const IMAGE_VIEWER_PREV = 'IMAGE_VIEWER_PREV';
